[features]
seeds = false
skip-lint = false
[programs.testnet]
r08_anchor_mintnft = "G4qmuKtjcULQBRx4XkkYa8iUpSmZDBGzns2ECp4Yv8N7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
