[features]
seeds = false
skip-lint = false
[programs.localnet]
transfer_pda_invoke_signed = "4eXeeKKDqW2e7TYycJ3p8vxK5hqLjkhRRvARcMMGbSWA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
