[features]
seeds = false
skip-lint = false
[programs.localnet]
pda_transfer_service_fee_lamports = "9P9KwpyHE7MmGXQMgkcYcWG3pUkPXq9VzpXrmReBoCTX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
