[features]
seeds = false
skip-lint = false
[programs.localnet]
basic_2 = "2Dm9UEFpx8kCf2y5viPpHnBxpvtpEot1EDdsPPb6UQJ7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
