[features]
seeds = false
skip-lint = false
[programs.localnet]
proxy_token = "7NgMh5nq6dceEVxMNjV4qqPAVZLkTErRajg9aBEhAUmF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
