[features]
seeds = false
skip-lint = false
[programs.localnet]
account_data = "rL11K4CD4RD7AYibz64DpTEQ2EDrs6GsmgaZErkxGx2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000